version: 0.2-CIBuild-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
clone_depth: 10
cache: C:/Users/appveyor/.conan/
environment:
  BUTLER_API_KEY:
    secure: PbT7/2muaC99K24vd6d+DMQETnal230eqmdPtw4tn+zqhwkKpSRIJgjRmJPxphBF
install:
- ps: >-
    git submodule update --init --recursive

    iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
    
    pip install conan

    scoop bucket add AFG https://github.com/AnotherFoxGuy/scoop-bucket.git

    scoop install sonar-build-wrapper-win sonar-scanner-msbuild
build_script:
- ps: >-
    cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release .

    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        SonarScanner.MSBuild begin /k:"cytopia" /d:"sonar.cfamily.build-wrapper-output=bw-output" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=$env:SONAR_LOGIN" /o:"cytopia" /v:"$env:APPVEYOR_BUILD_VERSION";
    }else{
        SonarScanner.MSBuild begin /k:"cytopia" /d:"sonar.analysis.mode=preview" /d:"sonar.cfamily.build-wrapper-output=bw-output" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=$env:SONAR_LOGIN" /o:"cytopia" /v:"$env:APPVEYOR_BUILD_VERSION" /d:"sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.github.repository=RigsOfRods/cytopia" /d:"sonar.github.oauth=$env:GITHUB_ACCESS_TOKEN"
    }
    
    build-wrapper-win-x86-64 --out-dir bw-output msbuild Cytopia.sln

    SonarScanner.MSBuild end /d:"sonar.login=$env:SONAR_LOGIN"
test_script:
- cmd: ctest

on_success:
- cmd: cmake -P cmake/pmm.cmake /Conan /Clean
